### ISSUE TITLE
Robot vacuum cleaner Pure 9.2 missing return home and powermodes

### ISSUE THREAD

**Issue by viwi1** [gslender/com.electrolux-aeg.ocp#13]
Missing the return home action. We have the stop/reset but it doesnt drive the robot home. 

Also missing powermodes. I want to be able to use silence/power mode when cleaning.

**Comment by gslender** [comment]
Yes, I will need to re-write the Exec Command specifically for the robot vacuum. Homey doesn't support dynamic capabilities that are variable depending on the device. AEG/Electrolux expect you to query the appliance for what it supports in terms of commands to execute, and then provide that list to the user. I can't do this with Homey and have to hard-code the list in the drop-down UI for Homey. This is annoying because it means that any changes in AEG/Electrolux will break the Homey app and/or fail to support various appliances etc.

Anyway, happy to add this for the Robot Vacuum, but wanted to vent my frustration at what I have to work with because the Homey interface is restrictive and doesn't offer a super flexible way to offer controls to the users.

Hopefully this will be fixed in future Homey updates.

**Comment by gslender** [comment]
Also, the PowerMode is only defined in the API as a number - probably 1, 2 or 3 - so I don't know what they are supposed to be in terms of a label. The code from the opensource you found has them as Low, Medium and High, but you've mentioned Silence as a possible value. I don't know if that's 1, 2 or 3 - or maybe Low means Silent ??

**Comment by gslender** [comment]
Looking at what the HASS guys have done, it looks like some complex mix of V2 of the API etc... 

https://github.com/Ekman/home-assistant-pure-i9/blob/master/custom_components/purei9/purei9.py

To be honest, it isn't easy to write the driver for this unless you can be really attentive to testing and get your hand dirty too with given logs and feedback. I'm going to pause here because without a device to test against, it really isn't viable for me to guess and make changes that I have no idea what result it produces

**Comment by gslender** [comment]
Without further feedback, I'm closing this
